In [11]:
import pandas as pd

df1=pd.read_csv('Covid.csv')
df1[160:200]

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
160,25-06-2021,India,309802519.0,27953093.0,55202.0,256135000.0,53667519.0,166996837.0,142754166.0,51516.0,...,108435293.0,110410673.0,90956553.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,26-06-2021,India,316535775.0,29924071.0,55142.0,261705883.0,54829892.0,170558604.0,145924320.0,52851.0,...,112960394.0,111903438.0,91671943.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,27-06-2021,India,318473492.0,14362704.0,23886.0,263289938.0,55183554.0,171570354.0,146849924.0,53214.0,...,114287302.0,112317011.0,91869179.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,28-06-2021,India,323836329.0,25874790.0,48855.0,267485789.0,56350540.0,174328759.0,149453113.0,54457.0,...,117673231.0,113624093.0,92539005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,29-06-2021,India,327685422.0,20606418.0,39263.0,270392224.0,57293198.0,176271011.0,151359083.0,55328.0,...,120044665.0,114600753.0,93040004.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,30-06-2021,India,330553623.0,18568866.0,33381.0,272487181.0,58066442.0,177750688.0,152746870.0,56065.0,...,121755682.0,115390323.0,93407618.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,01-07-2021,India,334913220.0,20310004.0,40094.0,275842378.0,59070842.0,180022023.0,154834173.0,57024.0,...,124412877.0,116539731.0,93960612.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,02-07-2021,India,339447068.0,20812325.0,40091.0,279132514.0,60314554.0,182375868.0,157013277.0,57923.0,...,126985291.0,117838292.0,94623485.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,03-07-2021,India,346054022.0,26140934.0,48778.0,283527017.0,62527005.0,185856473.0,160138342.0,59207.0,...,130761114.0,119730672.0,95562236.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,04-07-2021,India,347766247.0,12321517.0,19122.0,284750483.0,63015764.0,186748495.0,160958198.0,59554.0,...,131760228.0,120219354.0,95786665.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,05-07-2021,India,352412289.0,20486897.0,42139.0,287588808.0,64823481.0,189175605.0,163176110.0,60574.0,...,134087877.0,121768778.0,96555634.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,06-07-2021,India,356192949.0,17691841.0,35607.0,290132865.0,66060084.0,191160373.0,164971125.0,61451.0,...,136158617.0,122916328.0,97118004.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,07-07-2021,India,359728245.0,17449073.0,33655.0,292326546.0,67401699.0,193027060.0,166638938.0,62247.0,...,137996472.0,124050399.0,97681374.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,08-07-2021,India,363866177.0,18408867.0,37073.0,295113298.0,68752879.0,195194201.0,168608604.0,63372.0,...,140323602.0,125274577.0,98267998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,09-07-2021,India,367079052.0,15830443.0,31342.0,297184419.0,69894633.0,196883902.0,170130738.0,64412.0,...,142074586.0,126245273.0,98759193.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,10-07-2021,India,370921397.0,15975055.0,32091.0,299620148.0,71301249.0,198911398.0,171944765.0,65234.0,...,144140990.0,127450202.0,99330205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,11-07-2021,India,372249777.0,8835173.0,14717.0,300474970.0,71774807.0,199593430.0,172590906.0,65441.0,...,144850653.0,127867994.0,99531130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,12-07-2021,India,376350562.0,17301046.0,35603.0,303057816.0,73292746.0,201700141.0,174584012.0,66409.0,...,146972241.0,129180113.0,100198208.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,13-07-2021,India,380212639.0,15468942.0,33126.0,305477371.0,74735268.0,203712414.0,176432842.0,67383.0,...,148978156.0,130436240.0,100798243.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,14-07-2021,India,386288141.0,14758731.0,31235.0,310042014.0,76246127.0,206783170.0,179436493.0,68478.0,...,151234541.0,132856589.0,102197011.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,15-07-2021,India,390286930.0,16084911.0,35258.0,312624872.0,77662058.0,208881920.0,181335624.0,69386.0,...,153409838.0,134089039.0,102788053.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,16-07-2021,India,394641704.0,16935747.0,37143.0,315177274.0,79464430.0,211136743.0,183434678.0,70283.0,...,155648918.0,135521275.0,103471511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,17-07-2021,India,399873648.0,18405270.0,39857.0,318403675.0,81469973.0,213861867.0,185940424.0,71357.0,...,158454523.0,137167237.0,104251888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,18-07-2021,India,401441969.0,9120348.0,16236.0,319469878.0,81972091.0,214657889.0,186712441.0,71639.0,...,159352703.0,137615222.0,104474044.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,19-07-2021,India,406790133.0,19017782.0,42026.0,322905680.0,83884453.0,217407550.0,189309762.0,72821.0,...,162164065.0,139322155.0,105303913.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,20-07-2021,India,410430826.0,14830467.0,33503.0,325242678.0,85188148.0,219282113.0,191075012.0,73701.0,...,164156483.0,140448106.0,105826237.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,21-07-2021,India,412817034.0,11772741.0,23842.0,326792911.0,86024123.0,220516550.0,192226247.0,74237.0,...,165490766.0,141158729.0,106167539.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,22-07-2021,India,418366838.0,18416197.0,41363.0,330465663.0,87901175.0,223376425.0,194914788.0,75625.0,...,168588236.0,142841291.0,106937311.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,23-07-2021,India,422845298.0,16337977.0,37521.0,333352959.0,89492339.0,225676609.0,197091984.0,76705.0,...,171051873.0,144211690.0,107581735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,24-07-2021,India,428109930.0,18476847.0,40423.0,336917806.0,91192124.0,228432995.0,199598934.0,78001.0,...,174129036.0,145718727.0,108262167.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,25-07-2021,India,430170531.0,10784124.0,19973.0,338346937.0,91823594.0,229530717.0,200561391.0,78423.0,...,175393190.0,146262751.0,108514590.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,26-07-2021,India,436861480.0,22339305.0,46007.0,343039824.0,93821656.0,232940580.0,203840892.0,80008.0,...,179142928.0,148284870.0,109433682.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,27-07-2021,India,441128674.0,16549712.0,38079.0,345867755.0,95260919.0,235125348.0,205922411.0,80915.0,...,181617271.0,149496636.0,110014767.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,28-07-2021,India,445696580.0,0.0,0.0,349104325.0,96592255.0,237477784.0,208136635.0,82161.0,...,184431510.0,150689722.0,110575348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,29-07-2021,India,450997892.0,20051908.0,43876.0,352679959.0,98317933.0,240211089.0,210703313.0,83490.0,...,187633421.0,152107728.0,111256743.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,30-07-2021,India,456471250.0,20918871.0,45339.0,356348903.0,100122347.0,242983261.0,213403098.0,84891.0,...,190811644.0,153629017.0,112030589.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,31-07-2021,India,463113439.0,22141942.0,47334.0,361264651.0,101848788.0,246409497.0,216617587.0,86541.0,...,195087768.0,155232209.0,112793462.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,01-08-2021,India,467769865.0,9847327.0,20066.0,365110984.0,102658881.0,248763622.0,218919118.0,87125.0,...,197208754.0,156775004.0,113786107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,02-08-2021,India,473977156.0,22612516.0,47979.0,369654820.0,104322336.0,251922714.0,221965874.0,88568.0,...,201077466.0,158350312.0,114549378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,03-08-2021,India,480643928.0,23639645.0,47616.0,375040194.0,105603734.0,255277644.0,225275770.0,90514.0,...,205389843.0,159919512.0,115334573.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df=pd.DataFrame(df1)
df.describe()    # Task 1

,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
count,7.621000e+03,7.621000e+03,7621.000000,7.621000e+03,7.621000e+03,7.461000e+03,7.461000e+03,7461.000000,7.621000e+03,7.621000e+03,...,1.702000e+03,1.702000e+03,1.702000e+03,3.733000e+03,3.734000e+03,3.734000e+03,1.600000e+02,1.600000e+02,160.000000,5.919000e+03
mean,9.188171e+06,4.792358e+05,2282.872064,7.414415e+06,1.773755e+06,3.620156e+06,3.168416e+06,1162.978019,1.044669e+06,8.126553e+06,...,8.773958e+06,7.442161e+06,5.641605e+06,1.395895e+06,2.916515e+06,2.627444e+06,4.461687e+07,3.951018e+07,12370.543750,4.547842e+06
std,3.746180e+07,1.911511e+06,7275.973730,2.995209e+07,7.570382e+06,1.737938e+07,1.515310e+07,5931.353995,4.452259e+06,3.298414e+07,...,2.660829e+07,2.225999e+07,1.681650e+07,5.501454e+06,9.567607e+06,8.192225e+06,3.950749e+07,3.417684e+07,12485.026753,1.834182e+07
min,7.000000e+00,0.000000e+00,0.000000,7.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000,0.000000e+00,7.000000e+00,...,2.662400e+04,1.681500e+04,9.994000e+03,1.059000e+03,1.136000e+03,5.580000e+02,2.375700e+04,2.451700e+04,2.000000,7.000000e+00
25%,1.356570e+05,6.004000e+03,69.000000,1.166320e+05,1.283100e+04,5.655500e+04,5.210700e+04,8.000000,0.000000e+00,1.331340e+05,...,4.344842e+05,2.326275e+05,1.285605e+05,5.655400e+04,9.248225e+04,5.615975e+04,5.739350e+06,5.023407e+06,1278.750000,7.427550e+04
50%,8.182020e+05,4.547000e+04,597.000000,6.614590e+05,1.388180e+05,3.897850e+05,3.342380e+05,113.000000,1.185100e+04,7.567360e+05,...,3.095970e+06,2.695938e+06,1.805696e+06,2.947270e+05,8.330395e+05,7.887425e+05,3.716590e+07,3.365402e+07,8007.500000,4.022880e+05
75%,6.625243e+06,3.428690e+05,1708.000000,5.387805e+06,1.166434e+06,2.735777e+06,2.561513e+06,800.000000,7.579300e+05,6.007817e+06,...,7.366241e+06,6.969726e+06,5.294763e+06,9.105160e+05,2.499280e+06,2.337874e+06,7.441663e+07,6.685368e+07,19851.000000,3.501562e+06
max,5.132284e+08,3.501031e+07,73933.000000,4.001504e+08,1.130780e+08,2.701636e+08,2.395186e+08,98275.000000,6.236742e+07,4.468251e+08,...,2.243304e+08,1.667575e+08,1.186927e+08,9.224315e+07,9.096888e+07,6.731098e+07,1.349420e+08,1.156684e+08,46462.000000,2.506569e+08

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7845 entries, 0 to 7844
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Updated On                           7845 non-null   object
 1   State                                7845 non-null   object
 2   Total Doses Administered             7621 non-null   float64
 3   Sessions                             7621 non-null   float64
 4    Sites                               7621 non-null   float64
 5   First Dose Administered              7621 non-null   float64
 6   Second Dose Administered             7621 non-null   float64
 7   Male (Doses Administered)            7461 non-null   float64
 8   Female (Doses Administered)          7461 non-null   float64
 9   Transgender (Doses Administered)     7461 non-null   float64
 10   Covaxin (Doses Administered)        7621 non-null   float64
 11  CoviShield (Doses Administered)      7621 non-null   float64
 12  Sputnik V (Doses Administered)       2995 non-null   float64
 13  AEFI                                 5438 non-null   float64
 14  18-44 Years (Doses Administered)     1702 non-null   float64
 15  45-60 Years (Doses Administered)     1702 non-null   float64
 16  60+ Years (Doses Administered)       1702 non-null   float64
 17  18-44 Years(Individuals Vaccinated)  3733 non-null   float64
 18  45-60 Years(Individuals Vaccinated)  3734 non-null   float64
 19  60+ Years(Individuals Vaccinated)    3734 non-null   float64
 20  Male(Individuals Vaccinated)         160 non-null    float64
 21  Female(Individuals Vaccinated)       160 non-null    float64
 22  Transgender(Individuals Vaccinated)  160 non-null    float64
 23  Total Individuals Vaccinated         5919 non-null   float64
dtypes: float64(22), object(2)
memory usage: 1.4+ MB

In [14]:
df['State'].unique()

array(['India', 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu',
       'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh',
       'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
       'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
      dtype=object)

In [15]:
df.columns

Index(['Updated On', 'State', 'Total Doses Administered', 'Sessions',
       ' Sites ', 'First Dose Administered', 'Second Dose Administered',
       'Male (Doses Administered)', 'Female (Doses Administered)',
       'Transgender (Doses Administered)', ' Covaxin (Doses Administered)',
       'CoviShield (Doses Administered)', 'Sputnik V (Doses Administered)',
       'AEFI', '18-44 Years (Doses Administered)',
       '45-60 Years (Doses Administered)', '60+ Years (Doses Administered)',
       '18-44 Years(Individuals Vaccinated)',
       '45-60 Years(Individuals Vaccinated)',
       '60+ Years(Individuals Vaccinated)', 'Male(Individuals Vaccinated)',
       'Female(Individuals Vaccinated)', 'Transgender(Individuals Vaccinated)',
       'Total Individuals Vaccinated'],
      dtype='object')

In [16]:
print('Number of persons state wise vaccinated for first dose in India')
print('\n')                                                                     
df.groupby('State').sum()['First Dose Administered']

Number of persons state wise vaccinated for first dose in India

State
Andaman and Nicobar Islands                 1.642585e+07
Andhra Pradesh                              1.232861e+09
Arunachal Pradesh                           4.900498e+07
Assam                                       5.856002e+08
Bihar                                       1.470503e+09
Chandigarh                                  4.470310e+07
Chhattisgarh                                7.960029e+08
Dadra and Nagar Haveli and Daman and Diu    3.359506e+07
Delhi                                       6.243395e+08
Goa                                         7.599137e+07
Gujarat                                     2.131646e+09
Haryana                                     7.557984e+08
Himachal Pradesh                            3.162940e+08
India                                       2.826214e+10
Jammu and Kashmir                           4.101018e+08
Jharkhand                                   6.036737e+08
Karnataka                                   1.873330e+09
Kerala                                      1.193845e+09
Ladakh                                      1.780925e+07
Lakshadweep                                 4.363655e+06
Madhya Pradesh                              1.796605e+09
Maharashtra                                 2.784364e+09
Manipur                                     6.740957e+07
Meghalaya                                   6.261597e+07
Mizoram                                     4.787308e+07
Nagaland                                    4.241077e+07
Odisha                                      1.032633e+09
Puducherry                                  4.134686e+07
Punjab                                      5.843466e+08
Rajasthan                                   2.201044e+09
Sikkim                                      3.698093e+07
Tamil Nadu                                  1.288533e+09
Telangana                                   8.803206e+08
Tripura                                     1.926897e+08
Uttar Pradesh                               2.788411e+09
Uttarakhand                                 3.631914e+08
West Bengal                                 1.796450e+09
Name: First Dose Administered, dtype: float64

In [17]:
print('Number of persons state wise vaccinated for second dose in India')
print('\n')
df.groupby('State').sum()['Second Dose Administered']

Number of persons state wise vaccinated for second dose in India

State
Andaman and Nicobar Islands                 4.118554e+06
Andhra Pradesh                              3.588176e+08
Arunachal Pradesh                           1.193232e+07
Assam                                       1.307888e+08
Bihar                                       2.707906e+08
Chandigarh                                  1.159374e+07
Chhattisgarh                                1.721204e+08
Dadra and Nagar Haveli and Daman and Diu    4.594416e+06
Delhi                                       1.882189e+08
Goa                                         1.619817e+07
Gujarat                                     6.004184e+08
Haryana                                     1.586561e+08
Himachal Pradesh                            7.383858e+07
India                                       6.759621e+09
Jammu and Kashmir                           8.595165e+07
Jharkhand                                   1.221211e+08
Karnataka                                   4.271872e+08
Kerala                                      3.640488e+08
Ladakh                                      5.453762e+06
Lakshadweep                                 1.056446e+06
Madhya Pradesh                              3.169330e+08
Maharashtra                                 7.128811e+08
Manipur                                     1.185815e+07
Meghalaya                                   1.216663e+07
Mizoram                                     9.998418e+06
Nagaland                                    9.204637e+06
Odisha                                      2.513028e+08
Puducherry                                  8.608859e+06
Punjab                                      1.211210e+08
Rajasthan                                   4.917030e+08
Sikkim                                      9.723640e+06
Tamil Nadu                                  2.906706e+08
Telangana                                   1.981529e+08
Tripura                                     6.527014e+07
Uttar Pradesh                               5.544351e+08
Uttarakhand                                 1.000850e+08
West Bengal                                 5.861469e+08
Name: Second Dose Administered, dtype: float64

In [18]:
print('The Number of Males who have been vaccinated.')
df['Male (Doses Administered)'].sum()

The Number of Males who have been vaccinated.

27009983996.0

In [19]:
print('The Number of Females who have been vaccinated.')

df['Female (Doses Administered)'].sum()

The Number of Females who have been vaccinated.

23639554465.0